### ISSUE TITLE
function parameters

### ISSUE THREAD

**Issue by Entropy-Max** [keithmcnulty/wikifacts#5]
All the functions wiki_didyouknow(), wiki_inthenews() and wiki_onthisday() ... use date of format YMD as parameters , as it is required by Wikipedia main page. I just tried your package, and found that each function only randomly return one facts/news by using sample(1). If you can let user set this parameter  as n or ALL, First, Last etc to get the number of facts/news returned, it will be more flexible.

**Comment by keithmcnulty** [comment]
Done in dev version.
